/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wbj_jni_Jni */

#ifndef _Included_com_example_wbj_jni_Jni
#define _Included_com_example_wbj_jni_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wbj_jni_Jnic
 * Method:    getCInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_wbj_jni_Jni_getCInt
  (JNIEnv *, jobject);

/*
 * Class:     com_example_wbj_jni_Jni
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wbj_jni_Jni_getCString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_wbj_jni_Jni
 * Method:    getStatus
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_wbj_jni_Jni_getStatus
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_wbj_jni_Jni
 * Method:    getResponseCode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_wbj_jni_Jni_getResponseCode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
